trtframe:
  variables:
    ATLAS_LOCAL_ROOT_BASE: /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase
  script:
    - ls
    - set +e
    - source /cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/user/atlasLocalSetup.sh
    - mkdir ../build
    - cd ../build
    - asetup 21.2,AnalysisBase,latest
    - cmake ../xTRTFrame
    - make
